### ISSUE TITLE
Not just W8. And how do we implement your solution? 

### ISSUE THREAD

**Issue by FrankConijn** [lallousx86/KeyboardSpeedReset#1]
Hello, 

As you can see on the forum page you linked to yourself, the problem also occurs on XP, W7 and W10. Plus: how do we use your files? I'm savvy when it comes to general computer knowledge and web languages (HTML, CSS, PHP, Javascript), but I haven't got the foggiest idea on how to implement your solution. Could provide a step-by-step manual? You would help a large number of people with it.

**Comment by lallousx86** [comment]
Hi,

The program was distributed in source code form.

I have compiled it for you: https://github.com/lallousx86/KeyboardSpeedReset/raw/master/BINARIES/KeyboardSpeedReset.zip

Just unzip and run it.

You might want to add it to your system startup so it runs automatically when you reboot.
